mysite/blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
        url(r'^$', views.home, name='blog_home'),
    
]

mysite/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
from django.conf.urls import url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
     path('', include('accounts.urls')),
     path('blog', include('blog.urls')),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
	url(r'^create/$', views.order_create, name='order_create')
]

mysite/shop/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^shop/$', views.home, name='home'),
     url(r'^$', views.product_list, name='product_list'),
    url(r'^shop/(?P<category_slug>[-\w]+)/$',
        views.home, name='product_list_by_category'),

    url(r'^shop/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail, name='product_detail'),
]

mysite/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]


class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
	update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

mysite/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib.auth.decorators import login_required
@login_required
@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
	return redirect('cart:cart_detail')

@login_required
def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

@login_required
def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
	return render(request, 'cart/detail.html', {'cart': cart})

mysite/cart/templates/cart/detail.html
{% extends 'shop/base_shop.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart
{% endblock %}


{% block content %}


<section id="cart_items">
  <div class="container">
    <div class="breadcrumbs">
      <ol class="breadcrumb">
        <li><a href="{% url 'shop:product_list' %}">Home</a></li>
        <li class="active">Shopping Cart</li>
      </ol>
    </div>
    <div class="table-responsive cart_info">
      <table class="table table-condensed">
        <thead>
          <tr class="cart_menu">
            <td class="image">Image</td>
            <td class="description">Product</td>
            <td class="price">Price</td>
            <td class="quantity">Quantity</td>
            <td class="total">Total</td>
            <td class="total">Remove</td>

          </tr>
        </thead>
        <tbody>
          {% for item in cart %}
              {% with product=item.product  %}
          <tr>
            <td class="cart_product">
              <a href="{{ product.get__absolute_url }}">
                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto"></a>
            </td>
            <td class="cart_description">
              <h4><a href="">{{ product.name }}</a></h4>
              <p>{{ product.description }}</p>
            </td>
            <td class="cart_price">
              <p>CFA{{ item.price }}</p>
            </td>
            <td class="cart_quantity">
              <form action="{% url "cart:cart_add" product.id %}" method="post">
                  {% csrf_token %}
                  {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.update }}
                  <input type="submit" value="Update" class="btn btn-default update2">
              </form>
            </td>
            <td class="cart_total">
              <p class="cart_total_price">CFA{{ item.total_price }}</p>
            </td>
            <td class="cart_delete">
              <a class="cart_quantity_delete" href="{% url "cart:cart_remove" product.id %}"><i class="fa fa-times"></i></a>
            </td>
          </tr>
          {% endwith %}
      {% endfor %}
      <tr class="cart_menu">
          <td><b>Total</b></td>
          <td colspan="4"></td>
          <td colspan="num"><b>CFA{{ cart.get_total_price }}</b></td>
      </tr>

        </tbody>
      </table>
    </div>
  </div>
</section> <!--/#cart_items-->


<section id="do_action">
  <div class="container">
    <div class="heading">
      <h3>What would you like to do next?</h3>
      <p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <div class="chose_area">
          <ul class="user_option">
            <li>
              <input type="checkbox">
              <label>Use Coupon Code</label>
            </li>
            <li>
              <input type="checkbox">
              <label>Use Gift Voucher</label>
            </li>
            <li>
              <input type="checkbox">
              <label>Estimate Shipping & Taxes</label>
            </li>
          </ul>
          <ul class="user_info">
            <li class="single_field">
              <label>Country:</label>
              <select>
                <option>United States</option>
                <option>Bangladesh</option>
                <option>UK</option>
                <option>India</option>
                <option>Pakistan</option>
                <option>Ucrane</option>
                <option>Canada</option>
                <option>Dubai</option>
              </select>

            </li>
            <li class="single_field">
              <label>Region / State:</label>
              <select>
                <option>Select</option>
                <option>Dhaka</option>
                <option>London</option>
                <option>Dillih</option>
                <option>Lahore</option>
                <option>Alaska</option>
                <option>Canada</option>
                <option>Dubai</option>
              </select>

            </li>
            <li class="single_field zip-field">
              <label>Zip Code:</label>
              <input type="text">
            </li>
          </ul>
          <a class="btn btn-default check_out" href="">Get Quotes</a>
          <a class="btn btn-default check_out" href="{% url "orders:order_create" %}">Continue</a>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="total_area">
          <ul>
            <li>Cart Sub Total <span>CFA{{ cart.get_total_price }}</span></li>
            <li>Eco Tax <span>Free</span></li>
            <li>Shipping Cost <span>Free</span></li>
            <li>Total <span>CFA{{ cart.get_total_price }}</span></li>
          </ul>
          <a class="btn btn-default check_out" href="{% url "shop:product_list" %}">Continue Shopping</a>


            <a class="btn btn-default check_out" href="{% url "orders:order_create" %}">Check Out</a>
        </div>
      </div>
    </div>
  </div>
</section><!--/#do_action-->







    
{% endblock %}