mysite/blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
        url(r'^$', views.home, name='blog_home'),
    
]

mysite/cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as accounts_views
from django.conf.urls import url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('cart', include('cart.urls')),
    path('orders/', include('orders.urls')),
     path('', include('accounts.urls')),
     path('blog', include('blog.urls')),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
	url(r'^create/$', views.order_create, name='order_create')
]

mysite/shop/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'shop'

urlpatterns = [
    url(r'^shop/$', views.home, name='home'),
     url(r'^$', views.product_list, name='product_list'),
    url(r'^shop/(?P<category_slug>[-\w]+)/$',
        views.home, name='product_list_by_category'),

    url(r'^shop/(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail, name='product_detail'),
]

mysite/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True ,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
    	ordering = ('name', )
    	verbose_name = 'category'
    	verbose_name_plural = 'categories'
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    
    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

mysite/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required

@login_required
def home(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	# category_id = Category.objects.filter(name=new)
	products = Product.objects.filter(available=True)
	new_products = Product.objects.filter(category_id='12')
	sale_products = Product.objects.filter(category_id='13')
	recommend = Product.objects.filter(category_id='5')

	page = request.GET.get('page', 1)
	page2 = request.GET.get('page', 1)
	page3 = request.GET.get('page', 1)
	page4 = request.GET.get('page', 1)

	paginator = Paginator(products, 12)
	paginator2 = Paginator(new_products, 2)
	paginator3 = Paginator(sale_products, 1)
	paginator4 = Paginator(recommend, 3)


	try:
		product_list = paginator.page(page)
		product_list2 = paginator2.page(page2)
		product_list3 = paginator3.page(page3)
		product_list4 = paginator4.page(page4)



	except PageNotAnInteger:
		product_list = paginator.page(1)
		product_list2 = paginator2.page(1)
		product_list3 = paginator3.page(1)
		product_list4 = paginator4.page(1)


	except EmptyPage:
		product_list = paginator.page(paginator.num_pages)
		product_list2 = paginator2.page(paginator2.num_pages)
		product_list3 = paginator3.page(paginator3.num_pages)
		product_list4 = paginator4.page(paginator4.num_pages)






	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = Product.objects.filter(category=category)
		new_products = Product.objects.filter(category_id='12')
		sale_products = Product.objects.filter(category_id='13')
		recommend = Product.objects.filter(category_id='5')




		page = request.GET.get('page', 1)
		page2 = request.GET.get('page', 1)
		page3 = request.GET.get('page', 1)
		page4 = request.GET.get('page', 1)


		paginator = Paginator(products, 8)
		paginator2 = Paginator(new_products, 2)
		paginator3 = Paginator(sale_products, 1)
		paginator4 = Paginator(recommend, 3)

		try:
			product_list = paginator.page(page)
			product_list2 = paginator2.page(page2)
			product_list3 = paginator3.page(page3)
			product_list4 = paginator4.page(page4)


		except PageNotAnInteger:
			product_list = paginator.page(1)
			product_list2 = paginator2.page(1)
			product_list3 = paginator3.page(1)
			product_list4 = paginator4.page(1)





		except EmptyPage:
			product_list = paginator.page(paginator.num_pages)
			product_list2 = paginator2.page(paginator2.num_pages)
			product_list3 = paginator3.page(paginator3.num_pages)
			product_list4 = paginator4.page(paginator4.num_pages)

	context = {
		'category': category,
		'categories': categories,
		'product_list': product_list,
		'product_list2': product_list2,
		'product_list3': product_list3,
		'product_list4': product_list4
	}
	return render(request, 'shop/product/real_list.html', context)




def product_list(request, category_slug=None):
	category = None
	categories = Category.objects.all()
	# category_id = Category.objects.filter(name=new)
	products = Product.objects.filter(available=True)
	new_products = Product.objects.filter(category_id='12')
	sale_products = Product.objects.filter(category_id='13')
	recommend = Product.objects.filter(category_id='5')

	page = request.GET.get('page', 1)
	page2 = request.GET.get('page', 1)
	page3 = request.GET.get('page', 1)
	page4 = request.GET.get('page', 1)

	paginator = Paginator(products, 8)
	paginator2 = Paginator(new_products, 3)
	paginator3 = Paginator(sale_products, 3)
	paginator4 = Paginator(recommend, 3)


	try:
		product_list = paginator.page(page)
		product_list2 = paginator2.page(page2)
		product_list3 = paginator3.page(page3)
		product_list4 = paginator4.page(page4)



	except PageNotAnInteger:
		product_list = paginator.page(1)
		product_list2 = paginator2.page(1)
		product_list3 = paginator3.page(1)
		product_list4 = paginator4.page(1)


	except EmptyPage:
		product_list = paginator.page(paginator.num_pages)
		product_list2 = paginator2.page(paginator2.num_pages)
		product_list3 = paginator3.page(paginator3.num_pages)
		product_list4 = paginator4.page(paginator4.num_pages)






	if category_slug:
		category = get_object_or_404(Category, slug=category_slug)
		products = Product.objects.filter(category=category)
		new_products = Product.objects.filter(category_id='12')
		sale_products = Product.objects.filter(category_id='13')
		recommend = Product.objects.filter(category_id='5')




		page = request.GET.get('page', 1)
		page2 = request.GET.get('page', 1)
		page3 = request.GET.get('page', 1)
		page4 = request.GET.get('page', 1)


		paginator = Paginator(products, 8)
		paginator2 = Paginator(new_products, 3)
		paginator3 = Paginator(sale_products, 3)
		paginator4 = Paginator(recommend, 3)

		try:
			product_list = paginator.page(page)
			product_list2 = paginator2.page(page2)
			product_list3 = paginator3.page(page3)
			product_list4 = paginator4.page(page4)


		except PageNotAnInteger:
			product_list = paginator.page(1)
			product_list2 = paginator2.page(1)
			product_list3 = paginator3.page(1)
			product_list4 = paginator4.page(1)





		except EmptyPage:
			product_list = paginator.page(paginator.num_pages)
			product_list2 = paginator2.page(paginator2.num_pages)
			product_list3 = paginator3.page(paginator3.num_pages)
			product_list4 = paginator4.page(paginator4.num_pages)

	context = {
		'category': category,
		'categories': categories,
		'product_list': product_list,
		'product_list2': product_list2,
		'product_list3': product_list3,
		'product_list4': product_list4
	}
	return render(request, 'shop/product/list.html', context)

@login_required
def product_detail(request, id, slug):
	product = get_object_or_404(Product, id=id, slug=slug, available=True)
	recommend = Product.objects.filter(category_id='5')

	page4 = request.GET.get('page', 1)
	paginator4 = Paginator(recommend, 3)

	cart_product_form = CartAddProductForm()

	try:
		product_list4 = paginator4.page(page4)

	except PageNotAnInteger:
		product_list4 = paginator4.page(1)
	except EmptyPage:

		product_list4 = paginator4.page(paginator4.num_pages)


	context = {
		'product': product,
		'cart_product_form': cart_product_form,
		'product_list4': product_list4

	}
	return render(request, 'shop/product/detail.html', context)

mysite/shop/templates/shop/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Home | E-Shopper</title>

	<link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'static/css/font-awesome.min.css' %}" rel="stylesheet">
	<link href="{% static 'static/css/prettyPhoto.css' %}" rel="stylesheet">
	<link href="{% static 'static/css/price-range.css' %}" rel="stylesheet">
	<link href="{% static 'static/css/animate.css' %}" rel="stylesheet">
<link href="{% static 'static/css/main.css' %}" rel="stylesheet">
<link href="{% static 'static/css/responsive.css' %}" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
	<link rel="shortcut icon" href="{% static 'static/images/ico/favicon.ico' %}">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'static/images/ico/apple-touch-icon-144-precomposed.png' %}">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'static/images/ico/apple-touch-icon-114-precomposed.png' %}">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'static/images/ico/apple-touch-icon-72-precomposed.png' %}">
	<link rel="apple-touch-icon-precomposed" href="{% static 'static/images/ico/apple-touch-icon-57-precomposed.png' %}">

</head>
<body>
	{% include 'shop/navbar.html' %}



	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>

						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free E-Commerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'static/images/home/girl1.jpg' %}" class="girl img-responsive" alt="" />
									<img src="{% static 'static/images/home/pricing.png' %}"  class="pricing" alt="" />
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>100% Responsive Design</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'static/images/home/girl2.jpg' %}" class="girl img-responsive" alt="" />
									<img src="{% static 'static/images/home/pricing.png' %}"  class="pricing" alt="" />
								</div>
							</div>

							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free Ecommerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'static/images/home/girl3.jpg' %}" class="girl img-responsive" alt="" />
									<img src="{% static 'static/images/home/pricing.png' %}" class="pricing" alt="" />
								</div>
							</div>

						</div>

						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>

				</div>
			</div>
		</div>
	</section><!--/slider-->






	{% block content %}


	{% endblock %}

	<div class="container">
		<div class="row" style="margin-top: 6%">
			 <button class="btn btn-info pull-right">
				{% with totail_items=cart|length %}
					{% if cart|length > 0 %}
						My Shopping Order:
						<a href="{% url "cart:cart_detail" %}" style="color: #ffffff">
							{{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
						</a>
						{% else %}
						Your cart is empty.
					{% endif %}
				{% endwith %}
			 </button>
		</div>
	</div>

{% include 'shop/footer.html' %}
	<script src="{% static 'static/js/jquery.js' %}"></script>
<script src="{% static 'static/js/bootstrap.min.js' %}"></script>
<script src="{% static 'static/js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static 'static/js/price-range.js' %}"></script>
	<script src="{% static 'static/js/jquery.prettyPhoto.js' %}"></script>
	<script src="{% static 'static/js/main.js' %}"></script>
</body>
</html>

mysite/shop/templates/shop/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Home | E-Shopper</title>

	<link href="{% static 'static/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'static/css/font-awesome.min.css' %}" rel="stylesheet">
	<link href="{% static 'static/css/prettyPhoto.css' %}" rel="stylesheet">
	<link href="{% static 'static/css/price-range.css' %}" rel="stylesheet">
	<link href="{% static 'static/css/animate.css' %}" rel="stylesheet">
<link href="{% static 'static/css/main.css' %}" rel="stylesheet">
<link href="{% static 'static/css/responsive.css' %}" rel="stylesheet">
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<script src="js/respond.min.js"></script>
	<![endif]-->
	<link rel="shortcut icon" href="{% static 'static/images/ico/favicon.ico' %}">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'static/images/ico/apple-touch-icon-144-precomposed.png' %}">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'static/images/ico/apple-touch-icon-114-precomposed.png' %}">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'static/images/ico/apple-touch-icon-72-precomposed.png' %}">
	<link rel="apple-touch-icon-precomposed" href="{% static 'static/images/ico/apple-touch-icon-57-precomposed.png' %}">

</head>
<body>
	{% include 'shop/navbar.html' %}







	{% block content %}


	{% endblock %}

	

{% include 'shop/footer.html' %}
	<script src="{% static 'static/js/jquery.js' %}"></script>
<script src="{% static 'static/js/bootstrap.min.js' %}"></script>
<script src="{% static 'static/js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static 'static/js/price-range.js' %}"></script>
	<script src="{% static 'static/js/jquery.prettyPhoto.js' %}"></script>
	<script src="{% static 'static/js/main.js' %}"></script>
</body>
</html>

mysite/shop/templates/shop/navbar.html
{% load static %}
<header id="header"><!--header-->
  <div class="header_top"><!--header_top-->
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="contactinfo">
            <ul class="nav nav-pills">
              <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
              <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="social-icons pull-right">
            <ul class="nav navbar-nav">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header_top-->

  <div class="header-middle"><!--header-middle-->
    <div class="container">
      <div class="row">
        <div class="col-md-4 clearfix">
          <div class="logo pull-left">
            <a href="{% url 'shop:product_list' %}"><img src="{% static 'static/images/home/logo.png' %}" alt="" /></a>
          </div>
          <div class="btn-group pull-right clearfix">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                CAMEROON
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="">Canada</a></li>
                <li><a href="">UK</a></li>
                <li><a href="">USA</a></li>
              </ul>
            </div>

            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                CFA Franc BEAC
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="">Canadian Dollar</a></li>
                <li><a href="">Pound</a></li>
                <li><a href="">DOLLAR</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-8 clearfix">
          <div class="shop-menu clearfix pull-right">
            <ul class="nav navbar-nav">
              <li><a href=""><i class="fa fa-user"></i> Account</a></li>
              <li><a href=""><i class="fa fa-star"></i> Wishlist</a></li>
              <li><a href="{% url "orders:order_create" %}"><i class="fa fa-crosshairs"></i> Checkout</a></li>
              <li><a href="{% url 'cart:cart_detail'%}"><i class="fa fa-shopping-cart"></i> Cart</a></li>
              <li><a href="{% url 'signup'%}"><i class="fa fa-lock"></i> Login</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header-middle-->

  <div class="header-bottom"><!--header-bottom-->
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><a href="{% url 'shop:product_list' %}" class="active">Home</a></li>
              <li class="dropdown"><a href="{% url 'shop:home' %}">Shop<i class="fa fa-angle-down"></i></a>
                                  <ul role="menu" class="sub-menu">
                                      <li><a href="{% url 'shop:home' %}">Shop</a></li>
                                      <li><a href="{% url "orders:order_create" %}">Checkout</a></li>

                  <li><a href="{% url 'cart:cart_detail'%}">Cart</a></li>
                  <li><a href="{% url 'signup'%}">Login</a></li>
                                  </ul>
                              </li>
              <li class="dropdown"><a href="{% url 'blog_home'%}">Blog<i class="fa fa-angle-down"></i></a>
                                  <ul role="menu" class="sub-menu">
                                      <li><a href="{% url 'blog_home'%}">Blog List</a></li>
                  <li><a href="blog-single.html">Blog Single</a></li>
                                  </ul>
                              </li>
              <li><a href="404.html">404</a></li>
              <li><a href="contact-us.html">Contact</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="search_box pull-right">
            <input type="text" placeholder="Search"/>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header-bottom-->
</header><!--/header-->

mysite/shop/templates/shop/navbar_shop.html
{% load static %}
<header id="header"><!--header-->
  <div class="header_top"><!--header_top-->
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="contactinfo">
            <ul class="nav nav-pills">
              <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
              <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="social-icons pull-right">
            <ul class="nav navbar-nav">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header_top-->

  <div class="header-middle"><!--header-middle-->
    <div class="container">
      <div class="row">
        <div class="col-md-4 clearfix">
          <div class="logo pull-left">
            <a href="{% url 'shop:product_list' %}"><img src="{% static 'static/images/home/logo.png' %}" alt="" /></a>
          </div>
          <div class="btn-group pull-right clearfix">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                CAMEROON
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="">Canada</a></li>
                <li><a href="">UK</a></li>
                <li><a href="">USA</a></li>
              </ul>
            </div>

            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                CFA Franc BEAC
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="">Canadian Dollar</a></li>
                <li><a href="">Pound</a></li>
                <li><a href="">DOLLAR</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md-8 clearfix">
          <div class="shop-menu clearfix pull-right">
            <ul class="nav navbar-nav">
              <li><a href=""><i class="fa fa-user"></i> Account</a></li>
              <li><a href=""><i class="fa fa-star"></i> Wishlist</a></li>
              <li><a href="{% url 'shop:home' %}"><i class="fa fa-crosshairs"></i> Shop</a></li>
              <li><a href="{% url 'orders:order_create' %}"><i class="fa fa-crosshairs"></i> Checkout</a></li>
              <li><a href="{% url 'cart:cart_detail'%}"><i class="fa fa-shopping-cart"></i> Cart</a></li>
              <li><a href="{% url 'logout'%}"><i class="fa fa-lock"></i> Logout</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header-middle-->

  <div class="header-bottom"><!--header-bottom-->
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><a href="{% url 'shop:product_list' %}" >Home</a></li>
              <li class="dropdown"><a href="{% url 'shop:home' %}" class="active">Shop<i class="fa fa-angle-down"></i></a>
                                  <ul role="menu" class="sub-menu">
                                    <li><a href="{% url "shop:home" %}">Shop</a></li>
                                      <li><a href="{% url "orders:order_create" %}">Checkout</a></li>

                                    <li><a href="{% url 'cart:cart_detail'%}">Cart</a></li>
                                    <li><a href="{% url 'logout'%}">Logout</a></li>
                                  </ul>
                              </li>
              <li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                  <ul role="menu" class="sub-menu">
                                      <li><a href="blog.html">Blog List</a></li>
                  <li><a href="blog-single.html">Blog Single</a></li>
                                  </ul>
                              </li>
              <li><a href="404.html">404</a></li>
              <li><a href="contact-us.html">Contact</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="search_box pull-right">
            <input type="text" placeholder="Search"/>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header-bottom-->
</header><!--/header-->